project:
  type: book
  pre-render: quarto render template/prelims
  post-render: ./template/prelims/cleanup.bash

book:
  title: "Content-addressed Replicated Data Types"
  author: "Doran Penner"
  date: "May 2026"
  date-format: "MMMM YYYY"
  chapters:
    - index.qmd
    - chapters/distributed.qmd
    - chapters/crdt-intro.qmd
    - chapters/merkle-things.qmd
    - chapters/my-stuff.qmd
  appendices:
    - chapters/git-revisions.qmd

bibliography: extras/bibliography.bib
# for changing citation style or including all bibtex entries
# biblio-style: ieee
nocite: |
  @*

filters:
  - template/treesitter-highlighting.lua
  - quarto
  - template/remove-appendix-part.lua

# lof: true
# lot: true
abbrs:
  CRDT: Conflict-free replicated data type
  DAG: Directed acyclic graph
spectra:
  hash: |
    A *hash function* is a one-way function, which means it is easy to compute
    the output from the input but (ideally) computationally infeasible to
    compute the input from the output. Hash functions take an arbitrary
    input (of arbitrary length) and produce a fixed-length output that is
    deterministic based on the input but very hard to link back to it. They are
    commonly used to verify that a large input is unmodified. You hash (verb) an
    input to produce a hash (noun).
  graph: |
    A *graph* in math is a collection of things and lines between those things.
    The "things" themselves can be called nodes, vertices, or sometimes objects;
    the lines are called edges. This paper will mainly focus on *directed
    graphs*, which is when the edges have a direction from one vertex to the
    other.

division: Mathematics and Computer Science
thedivisionof: The Established Interdisciplinary Committee for
department: Mathematics and Computer Science
advisor: James Fix
altadvisor: Marcus Robinson

fontsize: 12pt

format:
  html:
    theme: cosmo
  pdf:
    documentclass: book
    realdocumentclass: template/reedthesis
    template: template/template.tex
    template-partials:
      - template/doc-class.tex
      - template/biblio.tex
    cite-method: biblatex
