project:
  render:
    - ../../extras/acknowledgements.qmd
    - ../../extras/preface.qmd
    - ../../extras/abstract.qmd
    - ../../extras/dedication.qmd

bibliography: extras/bibliography.bib

format:
  latex:
    template: template.tex
    cite-method: biblatex
